### PR TITLE
Fix SQL Scripts

### PR DESCRIPTION
**Pull request by realityfabric**
My original script didn't reflect all of the settings we set. I'm going to work on matching it more carefully.

I'll merge this when it's ready, feel free to provide feedback though.

### CODE REVIEW

**Comment by paigemax** [comment]
It looks like the 'id' column needs to be defined in the users table and set as the primary key?

id INT NOT NULL AUTO_INCREMENT,
PRIMARY KEY(id)

**Comment by realityfabric** [comment]
> It looks like the 'id' column needs to be defined in the users table and set as the primary key?
> 
> id INT NOT NULL AUTO_INCREMENT,
> PRIMARY KEY(id)

It's already [defined](https://github.com/CBC-CSIT316-F18/googaloo/blob/master/createDB.sql#L6), as

``` mySQL
id INT PRIMARY KEY AUTO_INCREMENT,
```

I didn't set ```NOT NULL``` because it's implied by the ```PRIMARY KEY``` constraint. Do we want to move the constraint to a separate line instead of how it is?

**Comment by paigemax** [comment]
Ah I see, it wasn't showing in the view I was looking at. Having it on the same line is how I usually do it, so I don't think it's an issue.

**Comment by realityfabric** [comment]
Do we have another place where the SQL scripts are located? They might also be inside of the files @TyckoFranklin uploaded from class, I haven't actually looked at those since I already had them outside of  www.

**Pull request merged**
